// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvMi6lylG_ZQsdjOsM7w84Exk_4hs_9Dk',
    appId: '1:240568061094:web:733923b17180484516b867',
    messagingSenderId: '240568061094',
    projectId: 'medora-9ccbd',
    authDomain: 'medora-9ccbd.firebaseapp.com',
    storageBucket: 'medora-9ccbd.firebasestorage.app',
    measurementId: 'G-38NXQZKDFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5NZsUD2xevCDnTkCeSWA9jqCRLDxXM0',
    appId: '1:240568061094:android:87acaedaa591b13a16b867',
    messagingSenderId: '240568061094',
    projectId: 'medora-9ccbd',
    storageBucket: 'medora-9ccbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy9VFmweTNxFkfE5zCKO-NumT32ntJVJo',
    appId: '1:240568061094:ios:9483596319c6faed16b867',
    messagingSenderId: '240568061094',
    projectId: 'medora-9ccbd',
    storageBucket: 'medora-9ccbd.firebasestorage.app',
    iosBundleId: 'com.bonnietech.medora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy9VFmweTNxFkfE5zCKO-NumT32ntJVJo',
    appId: '1:240568061094:ios:9483596319c6faed16b867',
    messagingSenderId: '240568061094',
    projectId: 'medora-9ccbd',
    storageBucket: 'medora-9ccbd.firebasestorage.app',
    iosBundleId: 'com.bonnietech.medora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvMi6lylG_ZQsdjOsM7w84Exk_4hs_9Dk',
    appId: '1:240568061094:web:0949c4da4e32091016b867',
    messagingSenderId: '240568061094',
    projectId: 'medora-9ccbd',
    authDomain: 'medora-9ccbd.firebaseapp.com',
    storageBucket: 'medora-9ccbd.firebasestorage.app',
    measurementId: 'G-WHCCGGBEYW',
  );
}
